services:
  checkus-server-dev:
    image: 855673866113.dkr.ecr.ap-northeast-2.amazonaws.com/checkus/server:dev
    ports:
      - 8081:8080
    restart: unless-stopped
    container_name: checkus-server-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - RDS_ENDPOINT=${RDS_ENDPOINT}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_DATABASE=${DEV_RDS_DATABASE:-checkus_dev}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_NOTIFICATION_CHANNEL_ID=${DISCORD_NOTIFICATION_CHANNEL_ID}
      - ADMIN_NAME=관리자
      - JWT_ACCESS_EXPIRATION=3600000
      - JWT_REFRESH_EXPIRATION=604800000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - JWT_SECRET=${JWT_SECRET}
      - BIZGO_CLIENT_ID=${BIZGO_CLIENT_ID}
      - BIZGO_CLIENT_PASSWORD=${BIZGO_CLIENT_PASSWORD}
      - BIZGO_SENDER_KEY=${BIZGO_SENDER_KEY}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - KIOSK_ADMIN_PASSWORD=${KIOSK_ADMIN_PASSWORD:-123456}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_CONSULTATION_ENABLED=${AI_CONSULTATION_ENABLED:-false}
      - TIRO_API_KEY=${TIRO_API_KEY}
      - TIRO_API_ENABLED=${TIRO_API_ENABLED:-false}
      - JAVA_OPTS=-Xmx350m -Xms150m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:G1HeapRegionSize=1M  # dev: 350MB (prod와 동일)
